language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
script:
- npm run build:server:production
- npm run build:client:production
- npm test
deploy:
  provider: heroku
  app: thinkful-full-stack-template
  api_key:
    secure: PRuLBhc6XywrftibqqQOthaTUMf2ne/VsdgXjNd4gHB/tPTYB4/h5d1kJktrlynQKo/FNpJsVIt3JHX1JfrfUb75C7rsSmV4NWZqNmWMO+npSPTWCaIm31GsUJYqVTtVr1aAF/7dosI2/hruvisBCpEbM/oKwOzxI8RMPEFPbEQDTEI4c0O+QLsQ1PEkr1/lkpMDkXwUSfFXG8171PdOErn92VYGoviqSHqLCYzh+Eb27umDmthN1gJh4IQ71BI1UYQnqvYAZLgVZ41ubFtTnttB5XBg9fOOEq7YyBCuXCe02+Z2u44B/m+dzMMDN7oOHBN1wLou3EFEheFS4asjB4cV5qinpmQdss2ySGOmBd/fsyBjK4NdHe4O0OhL4jw1Khdh2I9Pu5qyfGRV7DFcVcuVdj62pZ9TTQYz4uzKA8+SATZdqa0cWXgqmpdI7qvhpXUVway3i1w8EESIbhfdxCxsW2fRNEtS3hlF+nJaG35HDzzQJ1qOa9D22AJ/2BLqnXYi2LDI6YeI7+FtXsPoA54SEJgBDAOExSuKCrDnnubF0yrbRE5RQWEPJrPdJNCIJYpKosIdL9cLtiINt195ijA71SCe3a5vXkApJ5PL8q9ApIjvN5atvsES91F3hjCdl/qppgDMHTQ08W4uy3S7E6vHT8csx33jpVL2xAp9AzY=
